### ISSUE TITLE
Some separators look like vector gfx, some look rasterized

### ISSUE THREAD

**Issue by sateal** [cryptogogue/volition#10]
**Describe the bug**
When printing assets to pdf or on the printer, some flavor text separtors appear sharp and in-focus and others appear blurry.

**To Reproduce**
1. Go to inventory in the wallet.
2. Click on any print view
3. Print to PDF
4. Some of the separators in the flavor text are crisp and some are blurry.

**Expected behavior**
All separators should look the same when printed--preferably not blurry once printed.

**Screenshots**
<img width="1674" alt="Screen Shot 2020-03-17 at 4 52 56 PM" src="https://user-images.githubusercontent.com/8008287/76912438-1a4bf480-6871-11ea-8c7a-20bacfee0895.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 80

**Comment by sateal** [comment]
Text box in general is different for the cores than for the dudes/traps/etc. Also, core text box is one pixel too wide on the left side of the card.

**Comment by patrickmeehan** [comment]
This may be fixed now that print assets are all being explicitly rasterized.

**Comment by sateal** [comment]
Closing this as resolved. This is a browser print to PDF issue. Downloading rasterized images of assets and printing from the browser works as expected.
