### ISSUE TITLE
Errors on assets upon import in spite of being the exact same

### ISSUE THREAD

**Issue by TriAdX** [cryptogogue/volition#12]
fresh node (although this likely doesn't matter)

Publish Schema and Reset the attached schema
then, 
Publish Schema using the same schema. 

You get the following errors 

![image](https://user-images.githubusercontent.com/4472611/86611657-f8d85b00-bf7c-11ea-96a0-321d2621c500.png)

I thought that if an asset was exactly the same, it just "ignored" it, and that it only errored if the asset had different data.

[cardlist-working.xlsx](https://github.com/cryptogogue/volition/files/4879920/cardlist-working.xlsx)

**Comment by patrickmeehan** [comment]
This should be fixed on the -dev wallet.
