### ISSUE TITLE
attachGem macro not working

### ISSUE THREAD

**Issue by TriAdX** [cryptogogue/volition#14]
Publish and Reset using attached schema. Pull deck "Dev".
[cardlist-working.xlsx](https://github.com/cryptogogue/volition/files/4915620/cardlist-working.xlsx)

go to your assets (pull from inbox if needed)
use "Attach gem to host" method
Choose gem - "Delta Gem"
Choose host - "Beta Host"

inventory refreshes and nothing happened to Beta Host or Delta Gem, also no errors

This happens even if I use an old sheet that worked before.

**Comment by patrickmeehan** [comment]
Should be fixed. Please review.

**Comment by TriAdX** [comment]
This is acting the same way with the same steps as above. Wallet shows vol-wallet-js-app 0.1.17
