### ISSUE TITLE
Uppercase ID problem on assets/(asset id) endpoint

### ISSUE THREAD

**Issue by stl1988** [cryptogogue/volition#20]
If you scan a card's QR code which contaains the Asset ID in uppercase letters and use this in this endpoint, it will throw out a 502 Bad Gateway error.

If you use https://volition-node-beta.pancakehermit.com/assets/gohoz-todug-haran-229, it works just fine.
But if you use https://volition-node-beta.pancakehermit.com/assets/GOHOZ-TODUG-HARAN-229, it gives out a 502 error as of 2020-08-08 21:53 UTC.

**Comment by patrickmeehan** [comment]
Thank you, @stl1988! It should be fixed now. Please re-open if not.
