### ISSUE TITLE
Account rename back to previous name

### ISSUE THREAD

**Issue by TriAdX** [cryptogogue/volition#3]
**Describe the bug**
If you rename your account and then rename it back to a previously used name (for that account) it errors gracefully with "Alias already exists."
The old names are retaining their data.

**To Reproduce**
Rename your account. Rename it again back to the previous name

**Expected behavior**
I would expect to be able to return to a previous name unless someone else created an account in the meantime with that old name. I would expect the old account data to be lost once the new name is created. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 80.0.3987.100 (Official Build) (64-bit)

**Comment by patrickmeehan** [comment]
Must have been fixed. Now possible to reused names (but only for the same account).
